apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: u0c5ul63a-java-springboot
  janus-idp.io/tekton: u0c5ul63a-java-springboot
  backstage.io/kubernetes-id: u0c5ul63a-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u0c5ul63a-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
